name:                advent-of-code
version:             0.1.0.0
github:              "mazelife/advent-of-code"
license:             BSD3
author:              "James Stevenson"
copyright:           "2018 James Stevenson"
synopsis:            "Solutions to the 2018 Advent of Code Challenge"

extra-source-files:
- README.rst

data-files:
- data/day25.txt
- data/day24.txt


description:         Please see the README on GitHub at <https://github.com/mazelife/advent-of-code#readme>

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates

dependencies:
- base >= 4.7 && < 5
- containers
- text

library:
  source-dirs: src
  default-extensions: OverloadedStrings

executables:
  advent-of-code-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    default-extensions:
    - OverloadedStrings
    - GeneralizedNewtypeDeriving

tests:
  advent-of-code-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - test-framework
    - test-framework-hunit
    - HUnit
    default-extensions:
    - OverloadedStrings
    - GeneralizedNewtypeDeriving

